version: '3.5'

services:
  taiga:
    build: ./backend/
    ports:
      - 8000:8000
    environment:
      DEBUG: 'True' 
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: ''
      DATABASE_HOST: 'db'
      DATABASE_PORT: 5432
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
