version: '3.5'

services:
  taiga:
    build: .
    ports:
      - 8000:8000
      - 8080:80
    environment:
      DEBUG: 'True' 
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: ''
      DATABASE_HOST: 'db'
      DATABASE_PORT: 5432
      PUBLIC_REGISTER_ENABLED: 'True'
      EVENTS_PUSH_URL: "amqp://taiga:password@rabbitmq:5672/taiga" 
    depends_on:
      - db
      - rabbitmq
      - events
  db:
    image: postgres
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.7-alpine
    ports:
      - 5672:5672
      - 9000:8080
    environment:
      RABBITMQ_DEFAULT_USER: taiga 
      RABBITMQ_DEFAULT_PASS: password 
      RABBITMQ_DEFAULT_VHOST: taiga
  events:
    build: ./events
    ports:
      - 8888:8888
    depends_on:
      - rabbitmq


