version: '3.5'

services:
  taiga:
    build: .
    ports:
      - 8000:8000
      - 8080:80
    environment:
      DEBUG: 'True' 
      DATABASE_NAME: 'postgres'
      DATABASE_USER: 'postgres'
      DATABASE_PASSWORD: ''
      DATABASE_HOST: 'db'
      DATABASE_PORT: 5432
      PUBLIC_REGISTER_ENABLED: 'True'
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
